package:
    name: exa
    version: "0.2.15"

app:
    entry: exa

source:
    git_rev: v0.2.15
    git_url: https://github.com/exa-analytics/exa.git

requirements:
    build:
        - python x.x
        - numpy
        - scipy
        - matplotlib
        - sqlalchemy
        - pandas
        - networkx
        - sympy
        - seaborn
        - jupyter
        - notebook
        - ipywidgets
        - ipyparallel
        - sphinx
        - nose

    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - sqlalchemy
        - pandas
        - networkx
        - sympy
        - seaborn
        - jupyter
        - notebook
        - ipywidgets
        - ipyparallel
        - sphinx
        - nose

about:
    home: https://exa-analytics.github.io
    license: Apache 2.0
    license_file: LICENSE
    summary: A framework for data processing, analytics, and visualization.
