{% set name = "exa" %}
{% set version = "0.5.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/e/exa/exa-{{ version }}.tar.gz"

build:
  number: 0
  script: "python -m pip install . -vv" 

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numba>=0.50
    - numpy>=1.0
    - pandas>=1.0
    - networkx>=2.0
    - matplotlib>=3.0
    - pytest>=5.0
    - seaborn>=0.10
    - sympy>=1.5
    - pytables>=3.6
    - PyYAML>=5.3

test:
  imports:
    - exa

about:
    home: https://github.com/exa-analytics/{{ name }}.git
    license: Apache-2.0
    license_file: LICENSE
    summary: A framework for data science
