{% set name = "exa" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/exa-analytics/{{ name }}/archive/v{{ version }}.tar.gz

requirements:
  build:
    - python
    - setuptools

  run:
    - numba>=0.50
    - numpy>=1.0
    - pandas>=1.0
    - networkx>=2.0
    - matplotlib>=3.0
    - six>=1.0
    - pytest>=5.0
    - seaborn>=0.10
    - sympy>=1.5
    - pytables>=3.6

test:
  imports:
    - exa

about:
    home: https://exa-analytics.github.io/{{ name }}
    license: Apache-2.0
    license_file: LICENSE
    summary: A framework for data science
