{% set name = "exa" %}
{% set version = "0.4.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/exa-analytics/{{ name }}/archive/v{{ version }}.tar.gz

requirements:
  build:
    - python
    - setuptools

  run:
    - numpy
    - scipy
    - pandas
    - sympy
    - networkx
    - pytables
    - numba
    - six
    - ipython
    - matplotlib
    - seaborn

test:
  imports:
    - exa

about:
    home: https://exa-analytics.github.io/{{ name }}
    license: Apache-2.0
    license_file: LICENSE
    summary: A framework for data science
