package:
  name: exa
  version: "0.2.14"

source:
  git_rev: v0.2.14
  git_url: https://github.com/exa-analytics/exa.git

requirements:
  build:
    - python >=3.4
    - numpy
    - pandas >=0.18.1

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - sqlalchemy
    - pandas
    - networkx
    - sympy
    - seaborn
    - jupyter
    - notebook ==4.1
    - ipywidgets ==4.1
    - ipyparallel
    - sphinx
    - nose

about:
  home: https://github.com/exa-analytics/exa
  license: Apache 2.0
  license_file: LICENSE
