# -*- coding: utf-8 -*-
# Copyright (c) 2015-2017, Exa Analytics Development Team
# Distributed under the terms of the Apache License 2.0
"""
The purpose of this package is to provide a framework for reading data from disk,
organizing this data into related, systematic, and efficient data structures, and
attaching these data structures to a container to allow visualization and other
interactive exploration within the `Jupyter notebook`_. The following is a compact
summary.

- `editors`: Classes that facilitate creation of data containers
- `data`: Classes that facilitate data visualization via the container
- `containers`: Flexible device for processing, analyzing and visualizing data

Complete documentation is available on the web https://exa-analytics.github.io/exa/.
The following is a brief description of the source code structure, which may aid
in usage.

- :mod:`~exa.core.editor`: Generic editors
- :mod:`~exa.core.sections`: Section editors
- :mod:`~exa.core.parser`: Parsers
- :mod:`~exa.core.container`: Generic container

- :mod:`~exa.mpl`: Matplotlib wrappers
- :mod:`~exa.tex`: Text manipulation utilities
- :mod:`~exa.constants`: Physical constants
- :mod:`~exa.units`: Physical units
- :mod:`~exa.isotopes`: Chemical isotopes

- :mod:`~exa.spcial`: Singleton metaclass
- :mod:`~exa.core.base`: Abstract base classes

Note:
    Tests are always located in the ``tests`` directory of each package or
    sub-package.

.. _Jupyter notebook: https://jupyter.org/
"""
from ._version import __version__
from .core import Editor, Sections, Parser, Container
from . import mpl, tex, constants, units, isotopes


def _jupyter_nbextension_paths():
    """
    Automatically generated by the `cookiecutter`_.

    .. _cookiecutter: https://github.com/jupyter/widget-cookiecutter
    """
    return [{
        'section': "notebook",
        'src': "../build/widgets",
        'dest': "jupyter-exa",
        'require': "jupyter-exa/extension"
    }]
