# -*- coding: utf-8 -*-
# Copyright (c) 2015-2017, Exa Analytics Development Team
# Distributed under the terms of the Apache License 2.0
"""
This package provides core features of the Exa framework, specifically the
editor and container concepts.

- :mod:`exa._version`: Version information
- :mod:`exa.errors`: Error handling
- :mod:`exa.mpl`: Matplotlib wrappers
- :mod:`exa.tester`: Support for unit and doc tests
- :mod:`exa.tex`: Text manipulation utilities
- :mod:`exa.typed`: Strongly typed abstract base class

- :mod:`exa.core.__init__`: Editors, containers, and data objects
- :mod:`exa.physics.__init__`: Physical constants
"""
def _jupyter_nbextension_paths():
    """
    Automatically generated by the `cookiecutter`_.

    .. _cookiecutter: https://github.com/jupyter/widget-cookiecutter
    """
    return [{
        'section': "notebook",
        'src': "../build/widgets",
        'dest': "jupyter-exa",
        'require': "jupyter-exa/extension"
    }]

from ._version import __version__
from . import mpl, tex
from .editor import Editor, Sections, Section
from .container import FrameContainer
from .data import FrameData
