# -*- coding: utf-8 -*-
# Copyright (c) 2015-2016, Exa Analytics Development Team
# Distributed under the terms of the Apache License 2.0
"""
Job Table
#############
A :class:`~exa.cms.job.Job` is a single task, possibly within the context of a
:class:`~exa.cms.project.Project`. Jobs often are made up of a number of sub-jobs
and their organization is flexible and up to the user. Jobs may have generate
(and/or be generated by) multiple files.
"""
from sqlalchemy import String, Integer, ForeignKey, Table, Column
from sqlalchemy.orm import relationship
from exa.cms.base import Name, Time, Size, Base


job_file = Table('jobfile', Base.metadata,
                 Column('job_pkid', Integer, ForeignKey('job.pkid',
                                                        onupdate='CASCADE',
                                                        ondelete='CASCADE')),
                 Column('file_pkid', Integer, ForeignKey('file.pkid',
                                                         onupdate='CASCADE',
                                                         ondelete='CASCADE')))


class Job(Name, Time, Size, Base):
    """A single computational experiment that generates one or more files."""
    files = relationship('File', secondary=job_file, backref='jobs',
                         cascade='all, delete')
    @property
    def list_files(self):
        return self.files
